FROM python:3.10-slim

RUN apt update && apt install -y \
    build-essential \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.web.txt .
RUN pip install --upgrade pip && pip install -r requirements.web.txt

COPY web/ /app/

# Удаляем RUN collectstatic — он будет запускаться при старте
CMD ["bash", "-c", "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
