# Generated by Django 5.2.1 on 2025-05-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
