# Generated by Django 5.2.1 on 2025-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0004_messagethread_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagethread',
            options={},
        ),
        migrations.AddField(
            model_name='messagethread',
            name='avatar_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аватар (file_id)'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
