# Generated by Django 5.2.1 on 2025-05-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0005_alter_messagethread_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagethread',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='avatar_file_id',
        ),
        migrations.AddField(
            model_name='messagethread',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Аватар'),
        ),
    ]
